services:
  realtime.redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgres/data
        
volumes:
  postgres-data: